"""add checklist approval document compliance primitives

Revision ID: 74d016060875
Revises: e287bbcb3383
Create Date: 2026-08-07 23:46:10.666541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d016060875'
down_revision: Union[str, Sequence[str], None] = 'e287bbcb3383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CLOSED', name='approval_status', native_enum=False), nullable=False),
    sa.Column('current_assignee', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index('ix_approvals_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_id'), ['id'], unique=False)

    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_templates_id'), ['id'], unique=False)

    op.create_table('compliance_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_standards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_standards_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_compliance_standards_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CURRENT', 'SUPERSEDED', 'ARCHIVED', name='document_status', native_enum=False), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('file_ref', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supersedes_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_category'), ['category'], unique=False)
        batch_op.create_index('ix_documents_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('approval_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CLOSED', name='approval_status', native_enum=False), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CLOSED', name='approval_status', native_enum=False), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_events_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_events_id'), ['id'], unique=False)

    op.create_table('checklist_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='checklist_instance_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_instances', schema=None) as batch_op:
        batch_op.create_index('ix_checklist_instances_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_instances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_instances_template_id'), ['template_id'], unique=False)

    op.create_table('checklist_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('requires_evidence', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_template_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_template_items_template_id'), ['template_id'], unique=False)

    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parameter_name', sa.String(), nullable=True),
    sa.Column('operator', sa.Enum('LT', 'LTE', 'GT', 'GTE', 'EQ', 'BETWEEN', 'EXISTS', 'CUSTOM', name='compliance_operator', native_enum=False), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('threshold_min', sa.Float(), nullable=True),
    sa.Column('threshold_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('rule_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['compliance_standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_rules_standard_id'), ['standard_id'], unique=False)

    op.create_table('checklist_instance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('template_item_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('requires_evidence', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'PASS_', 'FAIL', 'NA', name='checklist_item_state', native_enum=False), nullable=False),
    sa.Column('evidence_ref', sa.String(), nullable=True),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['checklist_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_item_id'], ['checklist_template_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_instance_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_instance_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_instance_items_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_instance_items_template_item_id'), ['template_item_id'], unique=False)

    op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('measured_value', sa.Float(), nullable=True),
    sa.Column('result', sa.Enum('PASS_', 'FAIL', 'NOT_APPLICABLE', name='compliance_result', native_enum=False), nullable=False),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.create_index('ix_compliance_checks_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_checks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_checks_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_checks_rule_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_checks_id'))
        batch_op.drop_index('ix_compliance_checks_entity')

    op.drop_table('compliance_checks')
    with op.batch_alter_table('checklist_instance_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_instance_items_template_item_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_instance_items_instance_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_instance_items_id'))

    op.drop_table('checklist_instance_items')
    with op.batch_alter_table('compliance_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_rules_standard_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_rules_id'))

    op.drop_table('compliance_rules')
    with op.batch_alter_table('checklist_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_template_items_template_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_template_items_id'))

    op.drop_table('checklist_template_items')
    with op.batch_alter_table('checklist_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_instances_template_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_instances_id'))
        batch_op.drop_index('ix_checklist_instances_entity')

    op.drop_table('checklist_instances')
    with op.batch_alter_table('approval_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_events_id'))
        batch_op.drop_index(batch_op.f('ix_approval_events_approval_id'))

    op.drop_table('approval_events')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_family_id'))
        batch_op.drop_index('ix_documents_entity')
        batch_op.drop_index(batch_op.f('ix_documents_category'))

    op.drop_table('documents')
    with op.batch_alter_table('compliance_standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_standards_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_standards_code'))

    op.drop_table('compliance_standards')
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_templates_id'))

    op.drop_table('checklist_templates')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_id'))
        batch_op.drop_index('ix_approvals_entity')

    op.drop_table('approvals')
    # ### end Alembic commands ###
