"""create buildings floors rooms structural_elements

Revision ID: e287bbcb3383
Revises:
Create Date: 2026-07-20 20:17:52.013711

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e287bbcb3383"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("buildings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_buildings_id"), ["id"], unique=False)

    op.create_table(
        "floors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("floor_name", sa.String(), nullable=False),
        sa.Column("floor_number", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["building_id"], ["buildings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("floors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_floors_building_id"), ["building_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_floors_id"), ["id"], unique=False)

    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_name", sa.String(), nullable=False),
        sa.Column("room_number", sa.String(), nullable=True),
        sa.Column("room_type", sa.String(), nullable=True),
        sa.Column("floor_id", sa.Integer(), nullable=False),
        sa.Column("area", sa.Float(), nullable=True),
        sa.Column("occupancy", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["floor_id"], ["floors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rooms_floor_id"), ["floor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rooms_id"), ["id"], unique=False)

    op.create_table(
        "structural_elements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("element_name", sa.String(), nullable=False),
        sa.Column(
            "element_type",
            sa.Enum(
                "WALL",
                "BEAM",
                "COLUMN",
                "SLAB",
                "DOOR",
                "WINDOW",
                "STAIR",
                name="element_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("material", sa.String(), nullable=True),
        sa.Column("floor_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("dim_width", sa.Float(), nullable=True),
        sa.Column("dim_height", sa.Float(), nullable=True),
        sa.Column("dim_depth", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["floor_id"], ["floors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structural_elements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structural_elements_floor_id"), ["floor_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_structural_elements_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_structural_elements_room_id"), ["room_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("structural_elements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structural_elements_room_id"))
        batch_op.drop_index(batch_op.f("ix_structural_elements_id"))
        batch_op.drop_index(batch_op.f("ix_structural_elements_floor_id"))

    op.drop_table("structural_elements")
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rooms_id"))
        batch_op.drop_index(batch_op.f("ix_rooms_floor_id"))

    op.drop_table("rooms")
    with op.batch_alter_table("floors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_floors_id"))
        batch_op.drop_index(batch_op.f("ix_floors_building_id"))

    op.drop_table("floors")
    with op.batch_alter_table("buildings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_buildings_id"))

    op.drop_table("buildings")
    # ### end Alembic commands ###
